export const tabledata = [
  {
    familyid: "familyid_10050_02",
    product: "saving account",
    date: "2023-08-02",
    evebnttype: "graduation",
    name: "maurya",
    middlename: "ira",
  },
  {
    familyid: "familyid_10050_02",
    product: "saving account",
    date: "2023-08-02",
    evebnttype: "graduation",
    name: "maurya",
    middlename: "ira",
  },
  {
    familyid: "familyid_10050_02",
    product: "saving account",
    date: "2023-08-02",
    evebnttype: "graduation",
    name: "maurya",
    middlename: "ira",
  },
  {
    familyid: "familyid_10050_02",
    product: "saving account",
    date: "2023-08-02",
    evebnttype: "graduation",
    name: "maurya",
    middlename: "ira",
  },
  {
    familyid: "familyid_10050_02",
    product: "saving account",
    date: "2023-08-02",
    evebnttype: "graduation",
    name: "maurya",
    middlename: "ira",
  },
  {
    familyid: "familyid_10050_02",
    product: "saving account",
    date: "2023-08-02",
    evebnttype: "graduation",
    name: "maurya",
    middlename: "ira",
  },
  {
    familyid: "familyid_10050_02",
    product: "saving account",
    date: "2023-08-02",
    evebnttype: "graduation",
    name: "maurya",
    middlename: "ira",
  },
  {
    familyid: "familyid_10050_02",
    product: "saving account",
    date: "2023-08-02",
    evebnttype: "graduation",
    name: "maurya",
    middlename: "ira",
  },
  {
    familyid: "familyid_10050_02",
    product: "saving account",
    date: "2023-08-02",
    evebnttype: "graduation",
    name: "maurya",
    middlename: "ira",
  },
];
